# Concatenation

In [4]:
import pandas as pd
data1= {
    "ID":[1,2,3,4,5,6,7],
     "Name" :["Khadija","mona","mala","fazi","khadi","hadi","aniya"]
   }
df1 =pd.DataFrame(data1)
df1

   ID     Name
0   1  Khadija
1   2     mona
2   3     mala
3   4     fazi
4   5    khadi
5   6     hadi
6   7    aniya

In [5]:
data2={
    "ID":[11,25,13,4,5,63,77],
     "Marks":[76,88,69,86,92,68,95]
}
df2=pd.DataFrame(data2)
df2

   ID  Marks
0  11     76
1  25     88
2  13     69
3   4     86
4   5     92
5  63     68
6  77     95

### column wise conactenation

In [6]:
pd.concat([df1,df2],axis=1)

   ID     Name  ID  Marks
0   1  Khadija  11     76
1   2     mona  25     88
2   3     mala  13     69
3   4     fazi   4     86
4   5    khadi   5     92
5   6     hadi  63     68
6   7    aniya  77     95

### Row wise conactenation

In [7]:
pd.concat([df1,df2])

   ID     Name  Marks
0   1  Khadija    NaN
1   2     mona    NaN
2   3     mala    NaN
3   4     fazi    NaN
4   5    khadi    NaN
5   6     hadi    NaN
6   7    aniya    NaN
0  11      NaN   76.0
1  25      NaN   88.0
2  13      NaN   69.0
3   4      NaN   86.0
4   5      NaN   92.0
5  63      NaN   68.0
6  77      NaN   95.0

In [8]:
pd.concat([df1,df2],axis=0)  #by default row wis conact

   ID     Name  Marks
0   1  Khadija    NaN
1   2     mona    NaN
2   3     mala    NaN
3   4     fazi    NaN
4   5    khadi    NaN
5   6     hadi    NaN
6   7    aniya    NaN
0  11      NaN   76.0
1  25      NaN   88.0
2  13      NaN   69.0
3   4      NaN   86.0
4   5      NaN   92.0
5  63      NaN   68.0
6  77      NaN   95.0

# Groupby

In [10]:
import pandas as pd 
import numpy as np
data={
    "Name":["Faizan","Khadija","Aniya","Sultan"],
    "Department":["IT","HR","HR","IT",],
    "Salary":[90000,70000,50000,80000]
}
df =pd.DataFrame(data)
df

      Name Department  Salary
0   Faizan         IT   90000
1  Khadija         HR   70000
2    Aniya         HR   50000
3   Sultan         IT   80000

In [14]:
df.groupby("Department")["Salary"].mean() #Department wise average salary

Department
HR    60000.0
IT    85000.0
Name: Salary, dtype: float64

In [17]:
df.groupby("Department")["Salary"].agg(["mean","max","min","count"]) #multiple Agg

               mean    max    min  count
Department
HR          60000.0  70000  50000      2
IT          85000.0  90000  80000      2

In [19]:
df.groupby(["Department","Name"]).sum()

                    Salary
Department Name
HR         Aniya     50000
           Khadija   70000
IT         Faizan    90000
           Sultan    80000

# Discretization & Binning

In [25]:
ages =[12,18,25,30,45,70,5]
df =pd.DataFrame({"Age":ages})

###  Equal width Binning(pd.cut)

In [26]:
df["Age_Group"]=pd.cut(df["Age"],
                      bins=[0,18,30,50,80],
                      labels=["Teen","Young","Adult","Senoir"])

In [27]:
df

   Age Age_Group
0   12      Teen
1   18      Teen
2   25     Young
3   30     Young
4   45     Adult
5   70    Senoir
6    5      Teen

### Equal frequency Binning(pd.qcut)

In [29]:
df["Age_Group"] =pd.qcut(df["Age"],q=3)

In [30]:
df

   Age      Age_Group
0   12  (4.999, 18.0]
1   18  (4.999, 18.0]
2   25   (18.0, 30.0]
3   30   (18.0, 30.0]
4   45   (30.0, 70.0]
5   70   (30.0, 70.0]
6    5  (4.999, 18.0]

# Data Output/Saving

In [31]:
import pandas as pd
Ages =[12,18,25,30,45,60]
df=pd.DataFrame({"Ages":ages})

In [33]:
df.to_csv("file.csv",index=False)

In [34]:
pd.read_csv("file.csv")

   Ages
0    12
1    18
2    25
3    30
4    45
5    70
6     5