# Missing value/Data

In [2]:
import pandas as pd
import numpy as np

In [28]:
data={
    "name":["Ali","Sultan","Horia","Aniya","Hadi","Noor"],
    "Marks":[85,np.nan,78,None,65,0], 
     "City":["LHR","SHK","karachi","islamabad","FSD",None]
}
df=pd.DataFrame(data)
df

     name  Marks       City
0     Ali   85.0        LHR
1  Sultan    NaN        SHK
2   Horia   78.0    karachi
3   Aniya    NaN  islamabad
4    Hadi   65.0        FSD
5    Noor    0.0        NaN

In [29]:
df.isnull()

    name  Marks   City
0  False  False  False
1  False   True  False
2  False  False  False
3  False   True  False
4  False  False  False
5  False  False   True

In [30]:
df.isnull().sum()

name     0
Marks    2
City     1
dtype: int64

In [31]:
df.dropna()  #drop row which contain nan

    name  Marks     City
0    Ali   85.0      LHR
2  Horia   78.0  karachi
4   Hadi   65.0      FSD

In [33]:

df.dropna(subset=["Marks"])   # drop marks which contain nan value

    name  Marks     City
0    Ali   85.0      LHR
2  Horia   78.0  karachi
4   Hadi   65.0      FSD
5   Noor    0.0      NaN

# Filling Missing Values

### Fixed Value

In [40]:
data1={
    "Name":["Hania","Bilal","Shazia","Noor"],
    "Marks":[33,66,None,96],
    "City":["noorpur","SHK","LHR","FSD"]
}

In [41]:
df2=pd.DataFrame(data1)
df2

     Name  Marks     City
0   Hania   33.0  noorpur
1   Bilal   66.0      SHK
2  Shazia    NaN      LHR
3    Noor   96.0      FSD

In [42]:
df2["Marks"].fillna(10)

0    33.0
1    66.0
2    10.0
3    96.0
Name: Marks, dtype: float64

### Fill by Mean

In [45]:
df2["Marks"].fillna(df["Marks"].mean())

0    33.0
1    66.0
2    57.0
3    96.0
Name: Marks, dtype: float64

In [47]:
df2["City"].fillna(df["City"].mode()[0],inplace=True)

C:\Users\Wahab\AppData\Local\Temp\ipykernel_22188\1717954279.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df2["City"].fillna(df["City"].mode()[0],inplace=True)

0    noorpur
1        SHK
2        LHR
3        FSD
Name: City, dtype: str

In [48]:
import pandas as pd
import numpy as np

data = {
    "Name": ["Ali", "Sara", "Ahmed", "Hina","CR","Monkey"],
    "Marks": [85, np.nan, 78, None,65,0],
    "City": ["Lahore", "Karachi", None, "Islamabad","Lahore","Jungle"]
}

df3 = pd.DataFrame(data)
df3

     Name  Marks       City
0     Ali   85.0     Lahore
1    Sara    NaN    Karachi
2   Ahmed   78.0        NaN
3    Hina    NaN  Islamabad
4      CR   65.0     Lahore
5  Monkey    0.0     Jungle

### Fill By mode(Categorical Data)

In [50]:
df3["City"].fillna(df3["City"].mode()[0], inplace=True)

C:\Users\Wahab\AppData\Local\Temp\ipykernel_22188\4113078971.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df3["City"].fillna(df3["City"].mode()[0], inplace=True)

0       Lahore
1      Karachi
2       Lahore
3    Islamabad
4       Lahore
5       Jungle
Name: City, dtype: str

### Fill by median

In [52]:
df2

     Name  Marks     City
0   Hania   33.0  noorpur
1   Bilal   66.0      SHK
2  Shazia    NaN      LHR
3    Noor   96.0      FSD

In [53]:
df2["Marks"].fillna(df2["Marks"].median())

0    33.0
1    66.0
2    66.0
3    96.0
Name: Marks, dtype: float64

### Forward Fill(Copy Privous value)

In [54]:
df.ffill()

     name  Marks       City
0     Ali   85.0        LHR
1  Sultan   85.0        SHK
2   Horia   78.0    karachi
3   Aniya   78.0  islamabad
4    Hadi   65.0        FSD
5    Noor    0.0        FSD

### Backward Fill

In [55]:
df.bfill()

     name  Marks       City
0     Ali   85.0        LHR
1  Sultan   78.0        SHK
2   Horia   78.0    karachi
3   Aniya   65.0  islamabad
4    Hadi   65.0        FSD
5    Noor    0.0        NaN