In [2]:
import pandas as pd

In [6]:
a= [1,2,3]
n = pd.Series(a)
print(n)

0    1
1    2
2    3
dtype: int64

In [8]:
s= pd.Series([10,20,30],index=["a","b","c"])
print(s)

a    10
b    20
c    30
dtype: int64

In [9]:
print(s["a"])

10

In [10]:
data= {
    "Name":["Khadija","Malika","Noor"],
    "Name":["Khadija","Malika","Noor"],
    "Marks":[85,90,77],
    "City":["Faisalabad","Lahore","Karachi"]
}
df= pd.DataFrame(data)
print(df)

      Name  Marks        City
0  Khadija     85  Faisalabad
1   Malika     90      Lahore
2     Noor     77     Karachi

In [16]:
import pandas as pd
d = pd.read_csv("synthetic_mobile_sales_2025.csv")

In [18]:
d.head()

,Sale_ID,Brand,Model,Country,Storage,Color,Price_USD,Units_Sold,Revenue_USD,Customer_Rating,Payment_Method,Sale_Month,Sale_Year
0,1,Realme,Realme Model 2,UK,512GB,Gold,656,20,13120,3.7,Installments,11,2025
1,2,Vivo,Vivo Model 20,Australia,512GB,Blue,1013,9,9117,3.7,Debit Card,2,2025
2,3,Motorola,Motorola Model 12,Germany,512GB,White,1471,7,10297,3.1,Credit Card,2,2025
3,4,Vivo,Vivo Model 13,USA,512GB,Gold,1220,19,23180,3.6,Debit Card,6,2025
4,5,Vivo,Vivo Model 15,UAE,128GB,Silver,375,8,3000,4.4,Online Payment,1,2025

In [19]:
d.shape

(500, 13)

# *Selection And Indexing*

In [20]:
d[['Brand']]

        Brand
0      Realme
1        Vivo
2    Motorola
3        Vivo
4        Vivo
..        ...
495   OnePlus
496    Xiaomi
497      Vivo
498   Samsung
499    Xiaomi

[500 rows x 1 columns]

In [21]:
d['Brand']

0        Realme
1          Vivo
2      Motorola
3          Vivo
4          Vivo
         ...
495     OnePlus
496      Xiaomi
497        Vivo
498     Samsung
499      Xiaomi
Name: Brand, Length: 500, dtype: str

In [23]:
d[['Brand','Sale_ID']] #Selecting multiple column

        Brand  Sale_ID
0      Realme        1
1        Vivo        2
2    Motorola        3
3        Vivo        4
4        Vivo        5
..        ...      ...
495   OnePlus      496
496    Xiaomi      497
497      Vivo      498
498   Samsung      499
499    Xiaomi      500

[500 rows x 2 columns]

In [26]:
d.loc[0]

Sale_ID                         1
Brand                      Realme
Model              Realme Model 2
Country                        UK
Storage                     512GB
Color                        Gold
Price_USD                     656
Units_Sold                     20
Revenue_USD                 13120
Customer_Rating               3.7
Payment_Method       Installments
Sale_Month                     11
Sale_Year                    2025
Name: 0, dtype: object

In [27]:
d.loc[0,"Brand"]        #Row 0, name column

'Realme'

In [28]:
d.iloc[0,2]           #Row 1,column index 2

'Realme Model 2'

In [30]:
d[d["Price_USD"] > 80]

,Sale_ID,Brand,Model,Country,Storage,Color,Price_USD,Units_Sold,Revenue_USD,Customer_Rating,Payment_Method,Sale_Month,Sale_Year
0,1,Realme,Realme Model 2,UK,512GB,Gold,656,20,13120,3.7,Installments,11,2025
1,2,Vivo,Vivo Model 20,Australia,512GB,Blue,1013,9,9117,3.7,Debit Card,2,2025
2,3,Motorola,Motorola Model 12,Germany,512GB,White,1471,7,10297,3.1,Credit Card,2,2025
3,4,Vivo,Vivo Model 13,USA,512GB,Gold,1220,19,23180,3.6,Debit Card,6,2025
4,5,Vivo,Vivo Model 15,UAE,128GB,Silver,375,8,3000,4.4,Online Payment,1,2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,496,OnePlus,OnePlus Model 5,UK,128GB,Blue,371,10,3710,3.5,Debit Card,6,2025
496,497,Xiaomi,Xiaomi Model 4,Canada,128GB,Gold,414,8,3312,5.0,Installments,7,2025
497,498,Vivo,Vivo Model 9,Pakistan,256GB,Blue,314,17,5338,4.6,Cash,7,2025
498,499,Samsung,Samsung Model 19,France,128GB,Gold,342,1,342,4.5,Cash,6,2025
499,500,Xiaomi,Xiaomi Model 14,UK,64GB,Gold,1457,4,5828,3.2,Installments,9,2025

In [31]:
d[(d["Price_USD"] > 80) & (d["Country"] == "UK")]

,Sale_ID,Brand,Model,Country,Storage,Color,Price_USD,Units_Sold,Revenue_USD,Customer_Rating,Payment_Method,Sale_Month,Sale_Year
0,1,Realme,Realme Model 2,UK,512GB,Gold,656,20,13120,3.7,Installments,11,2025
9,10,Huawei,Huawei Model 6,UK,512GB,Gold,921,2,1842,4.8,Cash,3,2025
27,28,Huawei,Huawei Model 17,UK,256GB,Green,1395,6,8370,4.5,Credit Card,12,2025
53,54,Huawei,Huawei Model 8,UK,512GB,Silver,1409,1,1409,4.1,Installments,7,2025
74,75,Motorola,Motorola Model 6,UK,256GB,Green,754,8,6032,4.9,Credit Card,1,2025
77,78,Realme,Realme Model 5,UK,256GB,Blue,908,7,6356,4.6,Credit Card,2,2025
98,99,Google,Google Model 15,UK,512GB,Black,383,12,4596,4.8,Cash,7,2025
130,131,Google,Google Model 16,UK,512GB,Green,1088,7,7616,3.6,Online Payment,3,2025
139,140,OnePlus,OnePlus Model 7,UK,128GB,Gold,1482,10,14820,4.6,Cash,6,2025
149,150,Oppo,Oppo Model 7,UK,256GB,Gold,1118,7,7826,4.7,Cash,5,2025
154,155,Oppo,Oppo Model 7,UK,256GB,Green,1240,2,2480,4.1,Installments,8,2025
166,167,Oppo,Oppo Model 3,UK,512GB,Green,460,12,5520,3.6,Installments,11,2025
179,180,Realme,Realme Model 12,UK,512GB,Gold,477,7,3339,4.5,Credit Card,6,2025
186,187,Apple,Apple Model 13,UK,256GB,Blue,1279,16,20464,4.9,Debit Card,3,2025
189,190,Realme,Realme Model 8,UK,256GB,Green,361,1,361,3.8,Credit Card,8,2025
204,205,Apple,Apple Model 14,UK,128GB,White,322,6,1932,4.0,Installments,9,2025
206,207,Samsung,Samsung Model 19,UK,64GB,Silver,1198,6,7188,3.8,Cash,6,2025
225,226,Motorola,Motorola Model 8,UK,512GB,Gold,1115,15,16725,4.2,Credit Card,12,2025
231,232,Oppo,Oppo Model 3,UK,64GB,White,1084,3,3252,3.6,Installments,12,2025
235,236,Huawei,Huawei Model 12,UK,128GB,Silver,917,16,14672,3.6,Cash,8,2025
265,266,Motorola,Motorola Model 20,UK,64GB,Silver,1087,18,19566,3.5,Online Payment,9,2025
282,283,Apple,Apple Model 18,UK,128GB,Gold,1406,9,12654,3.1,Online Payment,9,2025
289,290,Oppo,Oppo Model 19,UK,64GB,White,1022,19,19418,4.2,Credit Card,5,2025
305,306,Google,Google Model 6,UK,256GB,Silver,480,18,8640,5.0,Debit Card,9,2025
310,311,Google,Google Model 12,UK,64GB,Gold,1058,4,4232,4.5,Debit Card,2,2025
315,316,Motorola,Motorola Model 18,UK,256GB,Black,539,1,539,3.7,Online Payment,10,2025
328,329,Oppo,Oppo Model 3,UK,64GB,Gold,1215,6,7290,4.6,Debit Card,6,2025
339,340,Apple,Apple Model 19,UK,128GB,White,1236,13,16068,4.6,Installments,6,2025
346,347,Motorola,Motorola Model 14,UK,128GB,White,528,20,10560,3.4,Installments,8,2025
351,352,OnePlus,OnePlus Model 7,UK,128GB,Black,1481,12,17772,3.1,Installments,10,2025
353,354,Google,Google Model 18,UK,128GB,Blue,1412,5,7060,3.8,Installments,2,2025
357,358,Apple,Apple Model 3,UK,64GB,White,826,9,7434,3.5,Installments,4,2025
368,369,Samsung,Samsung Model 5,UK,256GB,Black,715,4,2860,4.6,Debit Card,8,2025
369,370,Vivo,Vivo Model 7,UK,128GB,Gold,1310,1,1310,4.2,Cash,8,2025
371,372,Google,Google Model 17,UK,64GB,Gold,1284,17,21828,3.6,Online Payment,9,2025
384,385,Huawei,Huawei Model 5,UK,256GB,Silver,384,14,5376,4.0,Debit Card,2,2025
391,392,Samsung,Samsung Model 5,UK,128GB,Gold,1000,9,9000,4.7,Online Payment,8,2025
396,397,Xiaomi,Xiaomi Model 19,UK,64GB,White,1449,9,13041,3.8,Installments,7,2025
401,402,Oppo,Oppo Model 14,UK,64GB,Gold,569,9,5121,4.5,Debit Card,7,2025
407,408,Huawei,Huawei Model 5,UK,128GB,Blue,713,15,10695,4.8,Debit Card,2,2025
409,410,Realme,Realme Model 17,UK,128GB,Green,1227,6,7362,3.5,Credit Card,8,2025
410,411,Xiaomi,Xiaomi Model 17,UK,64GB,Gold,648,19,12312,4.4,Credit Card,4,2025
411,412,Motorola,Motorola Model 7,UK,128GB,Gold,574,5,2870,4.8,Debit Card,9,2025
431,432,Oppo,Oppo Model 7,UK,512GB,Silver,336,20,6720,4.8,Cash,8,2025
447,448,Xiaomi,Xiaomi Model 3,UK,512GB,Blue,1109,16,17744,4.1,Credit Card,8,2025
456,457,Motorola,Motorola Model 15,UK,64GB,Silver,538,3,1614,4.4,Online Payment,5,2025
461,462,Oppo,Oppo Model 5,UK,64GB,Green,772,14,10808,4.5,Cash,3,2025
478,479,Vivo,Vivo Model 8,UK,256GB,Black,729,6,4374,4.4,Online Payment,5,2025
495,496,OnePlus,OnePlus Model 5,UK,128GB,Blue,371,10,3710,3.5,Debit Card,6,2025
499,500,Xiaomi,Xiaomi Model 14,UK,64GB,Gold,1457,4,5828,3.2,Installments,9,2025

In [39]:
data= {
    "Name":["Khadija","Malika","Noor","Khadija"],
    "Marks":[85,90,77,None],
    "City":["Faisalabad","Lahore","Karachi","Shakot"]
}
df= pd.DataFrame(data)
print(df)

      Name  Marks        City
0  Khadija   85.0  Faisalabad
1   Malika   90.0      Lahore
2     Noor   77.0     Karachi
3  Khadija    NaN      Shakot

In [40]:
df.head(2)

      Name  Marks        City
0  Khadija   85.0  Faisalabad
1   Malika   90.0      Lahore

In [41]:
df["Name"].unique()

<StringArray>
['Khadija', 'Malika', 'Noor']
Length: 3, dtype: str

In [42]:
df["Name"].value_counts()

Name
Khadija    2
Malika     1
Noor       1
Name: count, dtype: int64

In [43]:
df.columns

Index(['Name', 'Marks', 'City'], dtype='str')

In [44]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [45]:
df.sort_values("Marks")

      Name  Marks        City
2     Noor   77.0     Karachi
0  Khadija   85.0  Faisalabad
1   Malika   90.0      Lahore
3  Khadija    NaN      Shakot

In [46]:
df.sort_values("Marks",ascending=False)

      Name  Marks        City
1   Malika   90.0      Lahore
0  Khadija   85.0  Faisalabad
2     Noor   77.0     Karachi
3  Khadija    NaN      Shakot

In [48]:
df.sort_values(["City"])

      Name  Marks        City
0  Khadija   85.0  Faisalabad
2     Noor   77.0     Karachi
1   Malika   90.0      Lahore
3  Khadija    NaN      Shakot

In [49]:
df.sort_values(["City","Marks"])

      Name  Marks        City
0  Khadija   85.0  Faisalabad
2     Noor   77.0     Karachi
1   Malika   90.0      Lahore
3  Khadija    NaN      Shakot

In [50]:
df.isnull()

    Name  Marks   City
0  False  False  False
1  False  False  False
2  False  False  False
3  False   True  False

In [51]:
df.isnull().sum()

Name     0
Marks    1
City     0
dtype: int64

In [53]:
df.dropna()    #Drop the raw which contains NaN values

      Name  Marks        City
0  Khadija   85.0  Faisalabad
1   Malika   90.0      Lahore
2     Noor   77.0     Karachi

In [54]:
df["City"].replace("Lahore","LHR")   #replace single city

0    Faisalabad
1           LHR
2       Karachi
3        Shakot
Name: City, dtype: str

In [55]:
df.replace({"Faisalabad":"FSD","Shakot":"SHK"})

      Name  Marks     City
0  Khadija   85.0      FSD
1   Malika   90.0   Lahore
2     Noor   77.0  Karachi
3  Khadija    NaN      SHK

In [56]:
df.drop("City",axis=1)

      Name  Marks
0  Khadija   85.0
1   Malika   90.0
2     Noor   77.0
3  Khadija    NaN

In [58]:
df.drop(0)

      Name  Marks     City
1   Malika   90.0   Lahore
2     Noor   77.0  Karachi
3  Khadija    NaN   Shakot

In [60]:
df.drop("City",axis=1,inplace=True)

In [61]:
df.head()

      Name  Marks
0  Khadija   85.0
1   Malika   90.0
2     Noor   77.0
3  Khadija    NaN

In [62]:
df.rename(columns={"Marks":"Score"})   #Rename the columns

      Name  Score
0  Khadija   85.0
1   Malika   90.0
2     Noor   77.0
3  Khadija    NaN

In [63]:
df["pass"] =df["Marks"] > 50 #Adding new column

In [64]:
df.head()

      Name  Marks   pass
0  Khadija   85.0   True
1   Malika   90.0   True
2     Noor   77.0   True
3  Khadija    NaN  False

# *Filling Missing Values*

#####  *Fixed Values Se Fill*

In [66]:
df["Marks"].fillna(0,inplace=True)

C:\Users\Wahab\AppData\Local\Temp\ipykernel_22260\510968332.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["Marks"].fillna(0,inplace=True)

0    85.0
1    90.0
2    77.0
3     0.0
Name: Marks, dtype: float64

##### fill by mean

In [67]:
df["Marks"].fillna(df["Marks"].mean(),inplace=True)

C:\Users\Wahab\AppData\Local\Temp\ipykernel_22260\2805342014.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["Marks"].fillna(df["Marks"].mean(),inplace=True)

0    85.0
1    90.0
2    77.0
3    84.0
Name: Marks, dtype: float64

#### Fill by Median

In [69]:
df["Marks"].fillna(df["Marks"].median(),inplace =True)

C:\Users\Wahab\AppData\Local\Temp\ipykernel_22260\3081166478.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["Marks"].fillna(df["Marks"].median(),inplace =True)

0    85.0
1    90.0
2    77.0
3    85.0
Name: Marks, dtype: float64

#### Fill By Mode(Categorical Data)

In [75]:
import pandas as pd
import numpy as np

data = {
    "Name": ["Mona", "Saira", "Ali", "Hina"],
    "Marks": [85, np.nan, 78, None],
    "City": ["Lahore", "Karachi", None, "FSD"]
}

df = pd.DataFrame(data)
print(df)

    Name  Marks     City
0   Mona   85.0   Lahore
1  Saira    NaN  Karachi
2    Ali   78.0      NaN
3   Hina    NaN      FSD

In [76]:
df["City"].fillna(df["City"].mode()[0])

0     Lahore
1    Karachi
2        FSD
3        FSD
Name: City, dtype: str