In [3]:
import pandas as pd
import numpy as np

##  *Merging*

In [5]:
data1= {
    "ID":[1,2,3,4,5,6,7],
     "Name" :["Khadija","mona","mala","fazi","khadi","hadi","aniya"]
   }
df1 =pd.DataFrame(data1)
df1

   ID     Name
0   1  Khadija
1   2     mona
2   3     mala
3   4     fazi
4   5    khadi
5   6     hadi
6   7    aniya

In [19]:
data2={
    "ID":[11,25,13,4,5,63,77],
     "Marks":[76,88,69,86,92,68,95]
}
df2=pd.DataFrame(data2)
df2

   ID  Marks
0  11     76
1  25     88
2  13     69
3   4     86
4   5     92
5  63     68
6  77     95

In [20]:
df = pd.merge(df1,df2,on="ID")

In [21]:
df

   ID   Name  Marks
0   4   fazi     86
1   5  khadi     92

# Types of Merging

## 1.Inner Join

In [22]:
pd.merge(df1,df2,on="ID",how="inner") #only contain common ID

   ID   Name  Marks
0   4   fazi     86
1   5  khadi     92

## outer join

In [25]:
pd.merge(df1,df2,on="ID",how="outer")   #1.contian all data  2.only unique values 3.left+right-common

    ID     Name  Marks
0    1  Khadija    NaN
1    2     mona    NaN
2    3     mala    NaN
3    4     fazi   86.0
4    5    khadi   92.0
5    6     hadi    NaN
6    7    aniya    NaN
7   11      NaN   76.0
8   13      NaN   69.0
9   25      NaN   88.0
10  63      NaN   68.0
11  77      NaN   95.0

## Left join

In [26]:
pd.merge(df1,df2,on="ID",how="left")

   ID     Name  Marks
0   1  Khadija    NaN
1   2     mona    NaN
2   3     mala    NaN
3   4     fazi   86.0
4   5    khadi   92.0
5   6     hadi    NaN
6   7    aniya    NaN

## Right Join

In [30]:
df1.join(df2,lsuffix="_left",rsuffix="_right")

   ID_left     Name  ID_right  Marks
0        1  Khadija        11     76
1        2     mona        25     88
2        3     mala        13     69
3        4     fazi         4     86
4        5    khadi         5     92
5        6     hadi        63     68
6        7    aniya        77     95